vertices    = [];
faultstruct = struct('vertices',[],'zt',[],'W',[],'dip',[],'L',[],'strike',[],'zone',[]);
otherstruct = [];
patchstruct = [];
data        = [];
boxx        = [];
boxy        = [];
zone        = 0;
dip         = 90;
W           = 20e3;
zt          = 0;
numver      = 0;
numdatas    = 0;
n           = 0;
numfaults   = 0;
otherflt    = 0;
onfault     = 0;
color       = [.8 .8 .8];
avg         = 10;

figh(1) = figure('Color',color, ...
	'Position',[800 660 500 500], ...
	'NumberTitle','off', ...
	'MenuBar','none', ...
        'Name','Fault Plot', ...
        'WindowButtonDownFcn','func=1;fault_buttons');

figh(2) = figure('Color',color, ...
	'Position',[100 660 500 250], ...
	'NumberTitle','off', ...
	'MenuBar','none', ...
        'Name','Make fault planes');

%%% file I/O
uicontrol('Position',[10 220 100 20], ...
	 'Callback','func=2;fault_buttons', ...
	 'String','Load mask file');
uicontrol('Position',[10 190 100 20], ...
	 'Callback','func=3;fault_buttons', ...
	 'String','Load unw file');
uicontrol('Position',[10 160 100 20], ...
	 'Callback','func=4;fault_buttons', ...
	 'String','Load struct');
uicontrol('Position',[10 100 100 20], ...
	 'Callback','func=5;fault_buttons', ...
	 'String','Load Fault Set');
uicontrol('Position',[10 70 100 20], ...
	 'Callback','func=6;fault_buttons', ...
	 'String','Save Fault Set');
uicontrol('Position',[430 160 60 20], ...
	 'Callback','func=7;fault_buttons', ...
	 'String','Done');


%%% point manipulation
uicontrol('BackgroundColor',color, ...
	'Parent',figh(2), ...
	'Position',[130 220 70 20], ...
	'String','Vertex #:', ...
	'Style','text');
fh(1)=uicontrol('Position',[210 220 60 20], ...
	'Callback','func=8;fault_buttons', ...
        'String','0', ...
	'Style','popupmenu');
uicontrol('BackgroundColor',color, ...
	'Position',[130 190 70 20], ...
	'String','x (m)', ...
	'Style','text');
fh(2) = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',[210 190 50 20], ...
	'String','0', ...
	'Style','edit');
uicontrol('BackgroundColor',color, ...
	'Position',[130 160 70 20], ...
	'String','y (m)', ...
	'Style','text');
fh(3) = uicontrol('BackgroundColor',[1 1 1], ...
	'Position',[210 160 50 20], ...
	'String','0', ...
	'Style','edit');
uicontrol('Position',[210 130 60 20], ...
	 'Callback','func=9;fault_buttons', ...
	 'String','Update');
uicontrol('Position',[210 100 60 20], ...
	 'Callback','func=10;fault_buttons', ...
	 'String','Delete');

%%% Params
uicontrol('BackgroundColor',color, ...
	  'Position',[280 220 80 20], ...
	  'String','zt (m)', ...
	  'Style','text');
uicontrol('BackgroundColor',color, ...
	  'Position',[280 190 80 20], ...
	  'String','Width (m)', ...
	  'Style','text');
uicontrol('BackgroundColor',color, ...
	  'Position',[280 160 80 20], ...
	  'String','Dip (deg)', ...
	  'Style','text');
uicontrol('BackgroundColor',color, ...
	  'Position',[280 130 80 20], ...
	  'String','Zone', ...
	  'Style','text');
uicontrol('BackgroundColor',color, ...
	  'Position',[280 100 80 20], ...
	  'String','img avg', ...
	  'Style','text');


fh(4) = uicontrol('BackgroundColor',[1 1 1], ...
		  'Callback','func=11;fault_buttons', ...
		  'Position',[360 220 50 20], ...
		  'String',num2str(zt), ...
		  'Style','edit');
fh(5) = uicontrol('BackgroundColor',[1 1 1], ...
		  'Callback','func=12;fault_buttons', ...
		  'Position',[360 190 50 20], ...
		  'String',num2str(W), ...
		  'Style','edit');
fh(6) = uicontrol('BackgroundColor',[1 1 1], ...
		  'Callback','func=13;fault_buttons', ...
		  'Position',[360 160 50 20], ...
		  'String',num2str(dip), ...
		  'Style','edit');
fh(7) = uicontrol('BackgroundColor',[1 1 1], ...
		  'Callback','func=14;fault_buttons', ...
		  'Position',[360 130 50 20], ...
		  'String',num2str(zone), ...
		  'Style','edit');
fh(8) = uicontrol('BackgroundColor',[1 1 1], ...
		  'Callback','func=15;fault_buttons', ...
		  'Position',[360 100 50 20], ...
		  'String',num2str(avg), ...
		  'Style','edit');

uicontrol('Position',[10 10 100 20], ...
	  'Callback','func=16;fault_buttons', ...
	 'String','Plot other');
